# =======================================================================
# Permissions
# =======================================================================
iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:SendMessageBatch
      - sqs:SendMessage
    Resource:
      - Fn::ImportValue: "${self:custom.stageName}-dead-letter-queue-arn"
  - Effect: Allow
    Action: cloudwatch:PutMetricData
    Resource: "*"
  - Effect: Allow
    Action:
      - sns:Publish
    Resource:
      - Fn::ImportValue: "${self:custom.stageName}-lambda-mailer-topic-arn"

# =======================================================================
# Environment Variables
# =======================================================================
environment:
  LOG_LEVEL: DEBUG
  STAGE_NAME: ${self:custom.stageName}
  APP_NAME: ${self:service}
  RECIPIENTS: ${env:ERROR_RECIPIENTS}
  SENDER: ${env:ERROR_SENDER}
  MAILER_TOPIC:
    Fn::ImportValue: "${self:custom.stageName}-lambda-mailer-topic-arn"


custom:
  stageName: ${opt:stage, self:provider.stage}
